"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['illicotuner.py']
DATA_FILES = ['/templates/device.xml']
OPTIONS = {'iconfile': 'illicoTuner.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
